# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: sudo npm install -g codeclimate-test-reporter
      - run: codeclimate-test-reporter < coverage/lcov.info

  deploy:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/repo
    environment:
      - AWS_REGION: eu-west-1
      - STAGE: production
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install serverless
          command: sudo npm install -g serverless
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: deploy
          command: serverless deploy --stage $STAGE --region $AWS_REGION
      - run:
          name: verify
          command: SLS_DEBUG=* serverless invoke --stage $STAGE --function integration_test
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
